from util import *

Mygene_map= {'HGNC': 'Str',
 'MIM': 'Str',
 'Vega': 'Str',
 '_id': 'Str',
 '_score': 'Float',
 'accession': {'genomic': ['Str'],
  'protein': ['Str'],
  'rna': ['Str'],
  'translation': [{'protein': 'Str', 'rna': 'Str'}]},
 'alias': ['Str'],
 'ec': 'Str',
 'ensembl': {'gene': 'Str',
  'protein': ['Str'],
  'transcript': ['Str'],
  'translation': [{'protein': 'Str', 'rna': 'Str'}]},
 'entrezgene': 'Int',
 'exac': {'all': {'exp_lof': 'Float',
   'exp_mis': 'Float',
   'exp_syn': 'Float',
   'lof_z': 'Float',
   'mis_z': 'Float',
   'mu_lof': 'Float',
   'mu_mis': 'Float',
   'mu_syn': 'Float',
   'n_lof': 'Float',
   'n_mis': 'Float',
   'n_syn': 'Float',
   'p_li': 'Float',
   'p_null': 'Float',
   'p_rec': 'Float',
   'syn_z': 'Float'},
  'bp': 'Int',
  'cds_end': 'Int',
  'cds_start': 'Int',
  'n_exons': 'Int',
  'nonpsych': {'exp_lof': 'Float',
   'exp_mis': 'Float',
   'exp_syn': 'Float',
   'lof_z': 'Float',
   'mis_z': 'Float',
   'mu_lof': 'Float',
   'mu_mis': 'Float',
   'mu_syn': 'Float',
   'n_lof': 'Float',
   'n_mis': 'Float',
   'n_syn': 'Float',
   'p_li': 'Float',
   'p_null': 'Float',
   'p_rec': 'Float',
   'syn_z': 'Float'},
  'nontcga': {'exp_lof': 'Float',
   'exp_mis': 'Float',
   'exp_syn': 'Float',
   'lof_z': 'Float',
   'mis_z': 'Float',
   'mu_lof': 'Float',
   'mu_mis': 'Float',
   'mu_syn': 'Float',
   'n_lof': 'Float',
   'n_mis': 'Float',
   'n_syn': 'Float',
   'p_li': 'Float',
   'p_null': 'Float',
   'p_rec': 'Float',
   'syn_z': 'Float'},
  'transcript': 'Str'},
 'exons': [{'cdsend': 'Int',
   'cdsstart': 'Int',
   'chr': 'Str',
   'position': ['Str'],
   'strand': 'Int',
   'transcript': 'Str',
   'txend': 'Int',
   'txstart': 'Int'}],
 'exons_hg19': [{'cdsend': 'Int',
   'cdsstart': 'Int',
   'chr': 'Str',
   'position': ['Str'],
   'strand': 'Int',
   'transcript': 'Str',
   'txend': 'Int',
   'txstart': 'Int'}],
 'generif': [{'pubmed': 'Int', 'text': 'Str'}],
 'genomic_pos': {'chr': 'Str',
  'end': 'Int',
  'ensemblgene': 'Str',
  'start': 'Int',
  'strand': 'Int'},
 'genomic_pos_hg19': {'chr': 'Str',
  'end': 'Int',
  'start': 'Int',
  'strand': 'Int'},
 'go': {
     'BP': [{'evidence': 'Str', 'id': 'Str', 'term': 'Str'}],
     'CC': [{'evidence': 'Str', 'id': 'Str', 'pubmed': 'Str','term': 'Str'}],
     'MF': [{'evidence': 'Str', 'id': 'Str', 'term': 'Str'}]
     },
 'homologene': {'genes': [['Int', 'Int']], 'id': 'Int'},
 'interpro': [{'desc': 'Str', 'id': 'Str', 'short_desc': 'Str'}],
 'ipi': ['Str'],
 'map_location': 'Str',
 'name': 'Str',
 'other_names': ['Str'],
 'pathway': {'biocarta': [{'id': 'Str', 'name': 'Str'}],
  'kegg': [{'id': 'Str', 'name': 'Str'}],
  'netpath': [{'id': 'Str', 'name': 'Str'}],
  'pid': [{'id': 'Str', 'name': 'Str'}],
  'reactome': [{'id': 'Str', 'name': 'Str'}],
  'wikipathways': [{'id': 'Str', 'name': 'Str'}]},
 'pdb': ['Str'],
 'pfam': 'Str',
 'pharmgkb': 'Str',
 'pir': 'Str',
 'prosite': 'Str',
 'reagent': {'GNF_Qia_hs-genome_v1_siRNA': [{'id': 'Str',
    'relationship': 'Str'}],
  'GNF_hs-ORFeome1_1_reads': {'id': 'Str', 'relationship': 'Str'},
  'GNF_hs-Origene': [{'id': 'Str', 'relationship': 'Str'}],
  'GNF_hs-druggable_lenti-shRNA': [{'id': 'Str', 'relationship': 'Str'}],
  'GNF_hs-druggable_plasmid-shRNA': [{'id': 'Str', 'relationship': 'Str'}],
  'GNF_hs-druggable_siRNA': [{'id': 'Str', 'relationship': 'Str'}],
  'GNF_hs-pkinase_IDT-siRNA': [{'id': 'Str', 'relationship': 'Str'}],
  'GNF_hs_LentiORF-HA-MYC': {'id': 'Str', 'relationship': 'Str'},
  'GNF_hs_LentiORF-Jred': {'id': 'Str', 'relationship': 'Str'},
  'GNF_mm+hs-MGC': {'id': 'Str', 'relationship': 'Str'},
  'Invitrogen_IVTHSSIPKv2': [{'id': 'Str', 'relationship': 'Str'}],
  'NIBRI_hs-Secretome_pDEST': {'id': 'Str', 'relationship': 'Str'},
  'NOVART_hs-genome_siRNA': [{'id': 'Str', 'relationship': 'Str'}]},
 'refseq': {'genomic': ['Str'],
  'protein': ['Str'],
  'rna': ['Str'],
  'translation': [{'protein': 'Str', 'rna': 'Str'}]},
 'reporter': {'HG-U133_Plus_2': ['Str'],
  'HG-U95Av2': ['Str'],
  'HTA-2_0': 'Str',
  'HuEx-1_0': 'Str',
  'HuGene-1_1': 'Str',
  'HuGene-2_1': 'Str'},
 'summary': 'Str',
 'symbol': 'Str',
 'taxid': 'Int',
 'type_of_gene': 'Str',
 'unigene': ['Str'],
 'uniprot': {'Swiss-Prot': 'Str', 'TrEMBL': ['Str']},
 'wikipedia': {'url_stub': 'Str'}}


Metadata_map = {'app_revision': 'Str',
                'genome_assembly':
                    {'fruitfly': 'Str',
                     'human': 'Str',
                     'rat': 'Str',
                     'zebrafish': 'Str',
                     'mouse': 'Str',
                     'frog': 'Str',
                     'pig': 'Str',
                     'nematode': 'Str'},
                'timestamp': 'Str',
                'src_version':
                    {'pharmgkb': 'Str',
                     'uniprot': 'Str',
                     'umls': 'Str',
                     'entrez': 'Str',
                     'exac': 'Str',
                     'ensembl': 'Int',
                     'ucsc': 'Str',
                     'refseq': 'Str',
                     'netaffy': 'Str',
                     'cpdb': 'Int'},
                'source': 'Str',
                'available_fields': 'Str',
                'stats':
                    {'total_species': 'Int',
                     'total_ensembl_genes_mapped_to_entrez': 'Int',
                     'total_ensembl_only_genes': 'Int',
                     'total_entrez_genes': 'Int',
                     'total_genes': 'Int',
                     'total_ensembl_genes': 'Int'},
                'taxonomy':
                    {'fruitfly': 'Int',
                     'human': 'Int',
                     'rat': 'Int',
                     'zebrafish': 'Int',
                     'mouse': 'Int',
                     'frog': 'Int',
                     'pig': 'Int',
                     'thale-cress': 'Int',
                     'nematode': 'Int'}}
Myvariant_map = {'_id': 'Str',
                 '_version': 'Int',
                 'cadd':
                     {'_license': 'Str',
                      'alt': 'Str',
                      'annotype': 'Str',
                      'bstatistic': 'Int',
                      'chmm': {'bivflnk': 'Int',
                               'enh': 'Int',
                               'enhbiv': 'Int',
                               'het': 'Int',
                               'quies': 'Int',
                               'reprpc': 'Int',
                               'reprpcwk': 'Int',
                               'tssa': 'Int',
                               'tssaflnk': 'Int',
                               'tssbiv': 'Int',
                               'tx': 'Int',
                               'txflnk': 'Int',
                               'txwk': 'Int',
                               'znfrpts': 'Int'},
                      'chrom': 'Int',
                      'consdetail': 'Str',
                      'consequence': 'Str',
                      'consscore': 'Int',
                      'cpg': 'Float',
                      'dna': {'helt': 'Float',
                              'mgw': 'Float',
                              'prot': 'Float',
                              'roll': 'Float'},
                      'encode': {'exp': 'Float',
                                 'h3k27ac': 'Float',
                                 'h3k4me1': 'Float',
                                 'h3k4me3': 'Float'},
                      'exon': 'Str',
                      'fitcons': 'Float',
                      'gc': 'Float',
                      'gene': {
                          'cds': {'cdna_pos': 'Int',
                                  'rel_cdna_pos': 'Float'},
                          'feature_id': 'Str',
                          'gene_id': 'Str',
                          'genename': 'Str'},
                      'gerp': {'n': 'Float', 's': 'Float'},
                      'isknownvariant': 'Str',
                      'istv': 'Str',
                      'length': 'Int',
                      'mapability': {'20bp': 'Int', '35bp': 'Int'},
                      'min_dist_tse': 'Int',
                      'min_dist_tss': 'Int',
                      'mutindex': 'Int',
                      'phast_cons': {'mammalian': 'Float', 'primate': 'Float', 'vertebrate': 'Float'},
                      'phred': 'Float',
                      'phylop': {'mammalian': 'Float', 'primate': 'Float', 'vertebrate': 'Float'},
                      'pos': 'Int',
                      'rawscore': 'Float',
                      'ref': 'Str',
                      'scoresegdup': 'Float',
                      'segway': 'Str',
                      'type': 'Str'},
                 'chrom': 'Str',
                 'hg19': {'end': 'Int', 'start': 'Int'},
                 'snpeff': {'_license': 'Str',
                            'ann': [{'distance_to_feature': 'Str',
                                     'effect': 'Str', 'feature_id': 'Str',
                                     'feature_type': 'Str',
                                     'gene_id': 'Str',
                                     'genename': 'Str',
                                     'hgvs_c': 'Str',
                                     'putative_impact': 'Str',
                                     'transcript_biotype': 'Str'}]},
                 'vcf': {'alt': 'Str',
                         'position': 'Str',
                         'ref': 'Str'}}

graphene_map = {
    'Str' : graphene.String,
    'Float' : graphene.Float,
    'Int' : graphene.Int
}
Mygene_map = cleared(Mygene_map)
Metadata_map = cleared(Metadata_map)
Myvariant_map = cleared(Myvariant_map)